version: 2

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: "Build Docker Image"
                command: "docker build -t ingalls/hecate:$CIRCLE_BRANCH ."
            - run: 
                name: "Tests"
                command: "docker run --env COMMITMSG=$(git log --format=oneline -n 1 $CIRCLE_SHA1) --env GITHUB_TOKEN=$GITHUB_TOKEN --name hecate ingalls/hecate:$CIRCLE_BRANCH"
